server:
  port: 8090

spring:
  jpa:
    database: mysql
    hibernate:
        ddl-auto: validate
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/millie?serverTimezone=Asia/Seoul
    username: root
    password:
